# Generated by Django 4.1.3 on 2022-11-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comandos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.EmailField(max_length=100)),
                ('descricao', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Olt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Onu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfils',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roteador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('transmissao', models.CharField(max_length=100)),
                ('emulador', models.CharField(default='Não Localizado', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('estagiario', models.CharField(default=0, max_length=100)),
                ('efetivo', models.CharField(default=0, max_length=100)),
                ('admin', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoteadorLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('roteador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FibrinoDev.roteador')),
            ],
        ),
    ]
