# Generated by Django 4.1.4 on 2022-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0002_apiauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIAuth',
        ),
        migrations.AddField(
            model_name='roteador',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
