# Generated by Django 4.1.4 on 2022-12-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0003_delete_apiauth_roteador_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfils',
            new_name='Perfis',
        ),
    ]
