# Generated by Django 4.1.4 on 2022-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0004_rename_perfils_perfis'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
    ]
