# Generated by Django 4.1.4 on 2022-12-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0005_olt_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandos',
            name='header',
            field=models.CharField(max_length=100),
        ),
    ]
