# Generated by Django 4.1.4 on 2022-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0006_alter_comandos_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandos',
            name='função',
            field=models.CharField(choices=[('Localizar ONU', 'Localizar ONU'), ('Verificar sinal da ONU', 'Verificar sinal da ONU'), ('Verificar quedas da ONU', 'Verificar quedas da ONU')], default=' ', max_length=100),
        ),
    ]
