# Generated by Django 4.1.4 on 2022-12-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0007_comandos_função'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandos',
            name='função',
            field=models.CharField(choices=[('Localizar ONU', 'Localizar ONU'), ('Verificar sinal da ONU', 'Verificar sinal da ONU'), ('Verificar quedas da ONU', 'Verificar quedas da ONU'), ('Verificar serviço da ONU', 'Verificar serviço da ONU'), ('Verificar se ONU está boiando', 'Verificar se ONU está boiando'), ('Verificando a primária', 'Verificando a primária'), ('Verificando sinal da primária', 'Verificando sinal da primária'), ('Verificando trafego da ONU', 'Verificando trafego da ONU')], default=' ', max_length=100),
        ),
    ]
