# Generated by Django 4.1.4 on 2022-12-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0008_alter_comandos_função'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandos',
            name='função',
            field=models.CharField(choices=[('Localizar ONU', 'Localizar ONU'), ('Verificar sinal da ONU', 'Verificar sinal da ONU'), ('Verificar quedas da ONU', 'Verificar quedas da ONU'), ('Verificar serviço da ONU', 'Verificar serviço da ONU'), ('Verificar se ONU está boiando', 'Verificar se ONU está boiando'), ('Verificar a primária', 'Verificar a primária'), ('Verificar sinal da primária', 'Verificar sinal da primária'), ('Verificar trafego da ONU', 'Verificar trafego da ONU'), ('Verificar cabo primário', 'Verificar cabo primário'), ('Verificar a VLAN', 'Verificar a VLAN'), ('Prolongar o Timed Out', 'Prolongar o Timed Out'), ('Reiniciar a ONU', 'Reiniciar a ONU'), ('Pesquisar a localização pela primária', 'Pesquisar a localização pela primária')], default=' ', max_length=100),
        ),
    ]
