# Generated by Django 4.1.4 on 2022-12-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0009_alter_comandos_função'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comandos',
            old_name='header',
            new_name='comando',
        ),
    ]
