# Generated by Django 4.1.4 on 2022-12-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FibrinoDev', '0011_alter_roteador_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteadorlogin',
            name='roteador_id',
            field=models.CharField(choices=[('Huawei', 'Huawei'), ('TP-link', 'TP-link'), ('Intelbras', 'Intelbras'), ('Mercusys', 'Mercusys')], max_length=100),
        ),
    ]
